[build]
publish = "."
functions = "functions"


[build.environment]
NODE_ENV = "production"


[[redirects]]
from = "/spotify/*"
to="/.netlify/functions/spotify/:splat"
status=200

[[redirects]]
from = "/spotify"
to="/.netlify/functions/spotify"
status=200